# Disease dictionary - maps disease predictions to descriptions
disease_dic = {
    'Apple___Apple_scab': 'Apple Scab: Apply fungicides and remove infected leaves.',
    'Apple___Black_rot': 'Apple Black Rot: Prune infected areas and apply fungicide.',
    'Apple___Cedar_apple_rust': 'Cedar Apple Rust: Remove nearby cedar trees if possible.',
    'Apple___healthy': 'Your apple plant appears to be healthy!',
    'Blueberry___healthy': 'Your blueberry plant appears to be healthy!',
    'Cherry_(including_sour)___Powdery_mildew': 'Powdery Mildew: Improve air circulation and apply fungicide.',
    'Cherry_(including_sour)___healthy': 'Your cherry plant appears to be healthy!',
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': 'Gray Leaf Spot: Use resistant varieties and apply fungicide.',
    'Corn_(maize)___Common_rust_': 'Common Rust: Apply fungicide during early stages.',
    'Corn_(maize)___Northern_Leaf_Blight': 'Northern Leaf Blight: Use resistant varieties and crop rotation.',
    'Corn_(maize)___healthy': 'Your corn plant appears to be healthy!',
    'Grape___Black_rot': 'Black Rot: Remove infected berries and apply fungicide.',
    'Grape___Esca_(Black_Measles)': 'Esca Disease: Prune infected wood and improve drainage.',
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': 'Leaf Blight: Apply fungicide and improve air circulation.',
    'Grape___healthy': 'Your grape plant appears to be healthy!',
    'Orange___Haunglongbing_(Citrus_greening)': 'Citrus Greening: Remove infected trees and control psyllid insects.',
    'Peach___Bacterial_spot': 'Bacterial Spot: Apply copper-based bactericides.',
    'Peach___healthy': 'Your peach plant appears to be healthy!',
    'Pepper,_bell___Bacterial_spot': 'Bacterial Spot: Use resistant varieties and copper sprays.',
    'Pepper,_bell___healthy': 'Your pepper plant appears to be healthy!',
    'Potato___Early_blight': 'Early Blight: Apply fungicide and practice crop rotation.',
    'Potato___Late_blight': 'Late Blight: Apply fungicide immediately and remove infected plants.',
    'Potato___healthy': 'Your potato plant appears to be healthy!',
    'Raspberry___healthy': 'Your raspberry plant appears to be healthy!',
    'Soybean___healthy': 'Your soybean plant appears to be healthy!',
    'Squash___Powdery_mildew': 'Powdery Mildew: Improve air circulation and apply fungicide.',
    'Strawberry___Leaf_scorch': 'Leaf Scorch: Improve watering practices and apply fungicide.',
    'Strawberry___healthy': 'Your strawberry plant appears to be healthy!',
    'Tomato___Bacterial_spot': 'Bacterial Spot: Use copper-based treatments and resistant varieties.',
    'Tomato___Early_blight': 'Early Blight: Apply fungicide and ensure good air circulation.',
    'Tomato___Late_blight': 'Late Blight: Apply fungicide immediately and remove infected plants.',
    'Tomato___Leaf_Mold': 'Leaf Mold: Improve ventilation and reduce humidity.',
    'Tomato___Septoria_leaf_spot': 'Septoria Leaf Spot: Apply fungicide and practice crop rotation.',
    'Tomato___Spider_mites Two-spotted_spider_mite': 'Spider Mites: Use insecticidal soap and improve humidity.',
    'Tomato___Target_Spot': 'Target Spot: Apply fungicide and remove infected leaves.',
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': 'Yellow Leaf Curl Virus: Control whiteflies and use resistant varieties.',
    'Tomato___Tomato_mosaic_virus': 'Tomato Mosaic Virus: Remove infected plants and disinfect tools.',
    'Tomato___healthy': 'Your tomato plant appears to be healthy!',
    'Model not available': 'Disease prediction model is not available. Please try again later.',
    'Error in prediction': 'There was an error processing your image. Please try again with a clear image.'
}
